name: Update CV
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/60 */12 * * *'
jobs:
  notebooks:
    name: "Update CV"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r cv_requirements.txt
          brew install gnupg
          
      - name: Decrypt token
        env:
          DRIVE_SECRET: ${{ secrets.JSON_TOKEN_SECRET}}
        run: |
          python scripts/decrypt_json.py
          
          
      - name: Update CV
        run: |
          # python scripts/scrape_google_scholar.py
          python scripts/update_cv.py
          
      - name: Remove token
        run: |
          rm token.json
          
          
      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CV
