name: Update CV
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs twice a day
   - cron:  '*/5 * * * *'
jobs:
  notebooks:
    name: "Update CV"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r cv_requirements.txt
          
      - name: Decrypt token
        env:
          DRIVE_SECRET: ${{ secrets.JSON_SECRET_KEY}}
        run: |
          python scripts/decrypt_json.py "$DRIVE_SECRET"
          
          
      - name: Update CV
        run: |
          python scripts/update_cv.py
          
      - name: Remove token
        run: |
          rm token.json
          
          
      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CV
